navikt/padm2

naiserator-dev.yaml, naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/Bootstrap.kt, src/main/kotlin/no/nav/syfo/Environment.kt, src/main/kotlin/no/nav/syfo/application/BlockingApplicationRunner.kt, src/main/kotlin/no/nav/syfo/client/AccessTokenClient.kt, src/main/kotlin/no/nav/syfo/client/PdfgenClient.kt, src/main/kotlin/no/nav/syfo/client/SyfohelsenettproxyClient.kt, src/main/kotlin/no/nav/syfo/handlestatus/HandleStatusInvalid.kt, src/main/kotlin/no/nav/syfo/handlestatus/HandleStatusOK.kt, src/main/kotlin/no/nav/syfo/model/PdfModel.kt, src/main/kotlin/no/nav/syfo/services/BehandlerService.kt, src/main/kotlin/no/nav/syfo/services/JournalService.kt, src/main/kotlin/no/nav/syfo/util/ExtractFromFellesFormat.kt, src/test/kotlin/no/nav/syfo/PdfModelTest.kt
Hent token fra azure med syfohelsenettproxy som audience
Hent behandler basert på signaturFnr fra syfohelsenettproxy
Send navn på behandler til padm2pdfgen
Nye godkjente leger i prod
=> Navn signaturlege

src/main/kotlin/no/nav/syfo/application/BlockingApplicationRunner.kt
Comment sending to eia code, in case we quickly need to go back
=> Process all messages from leger in padm2

build.gradle.kts, src/main/kotlin/no/nav/syfo/application/BlockingApplicationRunner.kt, src/main/kotlin/no/nav/syfo/client/DokArkivClient.kt, src/main/kotlin/no/nav/syfo/util/ImageUtils.kt
Convert image vedlegg to pdf, and store them in Joark as separate documents.
=> Image attachments to pdf

src/main/kotlin/no/nav/syfo/client/ArenaDialogNotat.kt, src/test/kotlin/no/nav/syfo/CreateArenaDialogNotatTest.kt
Fewer messages will end up in the backout queue
=> When tssid is missing from Kuhr Sar, use 0 in Arena

src/main/kotlin/no/nav/syfo/handlestatus/HandleStatusInvalid.kt
Brukere på Yammer stusser på kreativ blanding av nynorsk og bokmål
https://web.yammer.com/main/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMTA4MjA0MDE3NzM0NDUxMiJ9
=> Endrer feilmeldinger til å være på samme målform

build.gradle.kts
Should fix the following bug we've seen from time to time:
https://github.com/ktorio/ktor/issues/1815
=> Upgrade ktor 1.3.2 --> 1.5.1

build.gradle.kts, src/main/kotlin/no/nav/syfo/client/DokArkivClient.kt, src/test/kotlin/no/nav/syfo/client/DokArkivClientTest.kt
https://trello.com/c/4vU5utC2/261-dialogmeldinger-validere-respons-fra-joark
=> Håndtere feilsituasjoner fra Journalpostoppretting

.github/workflows/dispatch.yaml, README.md
Added some small changes in order to test deploy button feature for branches.
=> Test deploy button

src/main/kotlin/no/nav/syfo/client/DokArkivClient.kt
Ny PR-beskrivelse: Lag nytt filnavn uavhengig av beskrivelsen til vedlegget.
=> Make filnavn max 200 chars including filtype

src/main/kotlin/no/nav/syfo/client/ArenaDialogNotat.kt
=> Logge etter at melding til Arena er sendt, ikke før.

.github/workflows/kafka.yaml
Ref: https://doc.nais.io/persistence/kafka/manage_topics/#creating-topics-and-defining-access
=> Topic skal deklareres i gcp selv om app'en kjører på fss

src/main/kotlin/no/nav/syfo/client/ArenaDialogNotat.kt, src/main/kotlin/no/nav/syfo/kafka/DialogmeldingForKafka.kt, src/main/kotlin/no/nav/syfo/kafka/DialogmeldingProducer.kt, src/main/kotlin/no/nav/syfo/model/Dialogmelding.kt, src/main/kotlin/no/nav/syfo/model/DialogmeldingMapper.kt, src/test/kotlin/no/nav/syfo/PdfModelTest.kt, src/test/kotlin/no/nav/syfo/kafka/DialogmeldingProducerTest.kt
Må gjøre noen tilpasninger også i padm2pdfgen som må koordineres med denne.
=> Justerer innholdet i meldingen som legges på Kafka

src/main/kotlin/no/nav/syfo/Bootstrap.kt, src/main/kotlin/no/nav/syfo/application/BlockingApplicationRunner.kt
Da jeg tok bort logging av stack-trace (pga StackOverflow), så glemte jeg å tilpasse slik at exception-meldingen blir med i det som logges.
=> Include exception message in log-message

src/main/kotlin/no/nav/syfo/application/BlockingApplicationRunner.kt
Har testet i preprod: tidsstempel blir en time feil slik det er nå.
=> Store correct received timestamp

src/main/kotlin/no/nav/syfo/client/PdfgenClient.kt
Kan lage test for dette når den andre PR'en har blitt merget.
=> Check http status when generating pdf

build.gradle.kts
Snyk rapporter at commons-collection 3.2.1 har en sårbarhet.
=> Fix snyk-vulnerability (commons-collection via cxf)

.nais/naiserator-prod.yaml
Merger denne når databasen har blitt kopiert
=> Turn on message processing after migration to gcp

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Ref https://nav-it.slack.com/archives/C6W9E5GPJ/p1646837054110859
=> Oppdatere clientId for dokarkiv

src/main/kotlin/no/nav/syfo/client/DokArkivClient.kt, src/main/kotlin/no/nav/syfo/model/JournalpostRequest.kt, src/main/kotlin/no/nav/syfo/services/JournalService.kt, src/test/kotlin/no/nav/syfo/client/DokArkivClientTest.kt
Hvis hpr mangler, bruker vi fnr som tidligere.
=> Use HPR number as id for avsenderMottaker in journalpostRequest to Joark

.nais/naiserator-dev.yaml
Første test av in-place Postgres upgrade
=> Upgrade postgres to version 14 in dev

.nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/Bootstrap.kt
Skal merges når postgres upgrade er ferdig på GCP
=> Restart after Postgres14 upgrade

src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt, src/main/kotlin/no/nav/syfo/util/ExtractFromFellesFormat.kt, src/test/kotlin/no/nav/syfo/ExtractFromFellesFormatTest.kt
Log if behandler ident is not included in dialogmelding, or if it is different from fnr in avsender signature
=> Log behandler ident details

build.gradle.kts
Må ha med denne likevel, ellers dukker det opp en Critical i Snyk.
=> Fix snyk issues

.nais/kafka/dialogmelding.yaml
Tillate lesing av topic for innkommende dialogmeldinger
=> Add Kafka consumer

src/main/kotlin/no/nav/syfo/util/XMLDateTimeAdapter.kt, src/test/kotlin/no/nav/syfo/CreateArenaDialogNotatTest.kt, src/test/kotlin/no/nav/syfo/ExtractFromFellesFormatTest.kt, src/test/kotlin/no/nav/syfo/FromKiropraktorTest.kt
This fixes bug that parsed date strings without timezone information as UTC
=> Make sure xml date strings without timezone are parsed as LocalDate

.nais/alerts.yaml, src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
Forsøkt å oppdatere i henhold til https://doc.nais.io/observability/alerts/
Slack-kanalen som brukes er ikke lengre konfigurert i alert'en, men her: https://console.nav.cloud.nais.io/teams/teamsykefravr
=> Update alerts using PrometheusRule

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/Environment.kt, src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt, src/main/kotlin/no/nav/syfo/client/ClamAvClient.kt, src/main/kotlin/no/nav/syfo/handlestatus/HandleStatusInvalid.kt, src/main/kotlin/no/nav/syfo/model/ValidationResult.kt, src/main/kotlin/no/nav/syfo/services/VirusScanService.kt, src/test/kotlin/no/nav/syfo/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/dialogmelding/BlockingApplicationRunnerSpek.kt, src/test/kotlin/no/nav/syfo/mock/ClamAvMock.kt
Basert delvis på hvordan team sykmelding har gjort det:
https://github.com/navikt/pale-2/pull/47/files
=> virussjekk av vedlegg

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/Environment.kt, src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt, src/main/kotlin/no/nav/syfo/client/SmtssClient.kt, src/main/kotlin/no/nav/syfo/metrics/MetricRegistry.kt, src/test/kotlin/no/nav/syfo/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/mock/SmtssMock.kt
Get tss from both emottak and inftrygd endpoints, and compare both to kuhr sar.
Kuhr sar is still used, run in prod for a while to see if new endpoints are good enough.
=> Get tssId from team sykmelding app smtss

src/main/kotlin/no/nav/syfo/client/SmtssClient.kt
Fixes error where ktor responds with 400 Bad request. The illegal chars to replace are en dash, and em dash, to be replaced with hyphen.
=> Remove illegal chars in http header to smtss

build.gradle.kts, src/main/kotlin/no/nav/syfo/client/DokArkivClient.kt
Se https://trello.com/c/BdVv6umF
Mulig dette endrer tittel for alle dialogmeldinger (også de ifbm dialogmøter), så mulig vi må se litt mer på om vi skal ha en sjekk på hva slags meldingstype det er også. Kan la den stå åpen til folk er tilbake, så må de evt bare merge hvis jeg er på ferie 👍🏼
=> Update dialogmelding text

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/Bootstrap.kt, src/main/kotlin/no/nav/syfo/Environment.kt, src/main/kotlin/no/nav/syfo/application/mq/MqUtils.kt, src/test/kotlin/no/nav/syfo/TestEnvironment.kt
Har lagt til rette keystore på dev-gcp, må også gjøres på prod-gcp før merge.
Merge må koordineres med Akhtar, slik at TLS enables på MQ-kanalen samtidig med deploy til prod.
=> Use TLS for MQ

src/main/kotlin/no/nav/syfo/Bootstrap.kt
Turn on consumer after switch to TLS
=> Enable after switch to TLS

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt, src/main/kotlin/no/nav/syfo/client/LegeSuspensjonClient.kt, src/test/kotlin/no/nav/syfo/mock/LegeSuspensjonEndpointMock.kt
Btsys ønsker at vi går over til å bruke AzureAD og da kan vi også kalle de direkte. Kommer PR på å fjerne kode i https://github.com/navikt/isproxy
=> IS-1655: Call btsys directly

src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt, src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
=> Increase pdfgen timeout

.nais/naiserator-prod.yaml
Slår på sendingen i prod. 
Hvis alt går greit så blir neste PR å også sjekke mot isbehandlerdialog. 
Deretter blir det litt opprydning av toggle og annen kode knyttet til den synkrone sendingen til Arena som ikke lenger skal brukes 👍🏼
=> IS-1682: Enable toggle in prod

src/main/kotlin/no/nav/syfo/application/SendDialogmeldingArenaAdhocCronjob.kt, src/main/kotlin/no/nav/syfo/application/cronjob/CronjobLauncher.kt, src/main/kotlin/no/nav/syfo/persistering/db/PersisterDialogmeldingQueries.kt
Sender 64 meldinger fra 2023-10-27 til Arena
=> IS-1739: Resende 64 meldinger til Arena

src/main/kotlin/no/nav/syfo/client/ClamAvClient.kt
Tror dette skal fikse meldingen som feiler nå.
=> IS-1849: Remove lf from vedlegg name

build.gradle.kts
=> Upgrade dependencies

.nais/kafka/dialogmelding.yaml
Gi datavarehus tilgang til å lese dialogmeldinger topic
=> IS-2081: Give dvh read access to topic

src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
Hva er nytt / hva har blitt fikset?
=> Increase socket timeout pdfgen

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
https://nav-it.slack.com/archives/C012X71FN04/p1713185536067369
=> IS-2301: Btsys migrert til gcp

src/main/kotlin/no/nav/syfo/model/Behandler.kt, src/main/kotlin/no/nav/syfo/model/Dialogmelding.kt
Ref: https://trello.com/c/qi5fSlkC/2276-korrigere-hvordan-vi-viser-lagrer-avsender-i-padm2
=> IS-2276: Endrer format på navn som brukes til avsenderMottaker-feltet i journalføring

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, README.md, build.gradle.kts, gradle.properties, src/main/kotlin/no/nav/syfo/application/BackgroundTask.kt, src/main/kotlin/no/nav/syfo/application/api/authentication/ApiAuthenticationFeature.kt
Hva er nytt / hva har blitt fikset?
* Oppgradert gradle wrapper til 8.10
* Satt riktig tier for databasene
* Fjernet bruk av githubUser og githubPassword, bruker NAVs mirror av github-package-registry i navikt orgen
* Rydder opp i README.md nå java 21
* Legger til kotlin.daemon.jvmargs=-Xmx1024m for at gradle skal få nok minne
=> chore: upgrade and clean up

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
=> IS-2223: Use ispdfgen

.nais/naiserator-prod.yaml, Dockerfile
Får OOM på pdf-konverting av jpeg-vedlegg i prod
=> Increase heap size

src/main/resources/db/migration/V5_7__reprocess_message.sql
Reprosesser en dialogmelding slik at det blir lagt på Kafka på nytt: da vil vi få opprettet det manglende kontoret (dvs etter de siste tilpasningene i isdialogmelding).
=> IS-3207: Reprocess dialogmelding

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
=> IS-3305: Kibana
