navikt/padm2

- src/main/kotlin/no/nav/syfo/client/KuhrSarClient.kt
- src/main/kotlin/no/nav/syfo/client/Padm2ReglerClient.kt
Tidligere har vi prøvd å mappe om til objekt med én gang, men hvis vi får en feilmelding av type text tilbake, klarer vi ikke å konvertere fordi det ikke er json, og vi ender opp med en exception.
Nå sjekker vi hva status er før vi mapper om til objekt, eller kaster exception.
> Handle errors from external api calls, with retry when appropriate

- src/main/kotlin/no/nav/syfo/model/DialogmeldingMapper.kt
- src/test/resources/dialogmelding_dialog_notat.xml
This is necessary because EPJs were allowed to send incorrect data to
previous system EIA. Even if the EPJ did send correct XML we're currently
not using the information.
In the future, when we start threading messages, we'll need to make sure
they also send the required information to identify the original message
they're responding to.
> Ignore Foresporsel tag in XML of type dialog_notat/henvendelse fra lege

- src/main/kotlin/no/nav/syfo/client/DokArkivClient.kt
Da vil vi unngå at lagring i Joark feiler pga ugyldig Dokument.
Dette gjør at dialogmeldingen vil gå gjennom som normalt, uten feil, men ingen får beskjed om at vi har ignorert det tomme vedlegget.
> Filter out empty vedlegg before creating Dokumenter

- redis.yaml
No more than 1 replica works with NAIS.
> Fix number of replicas for redis

- .github/workflows/dispatch.yaml
Set up java, run tests and build a jar package before building and
publishing the docker image. The build docker image step runs the
app's Docker file, which requires a jar file to work.
Also switch to actions/checkout@v2, it should be quicker, see
https://github.com/actions/checkout
> Build jar first, then build and push docker image.

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/application/BlockingApplicationRunner.kt
- src/main/kotlin/no/nav/syfo/handlestatus/HandleStatusInvalid.kt
- src/main/kotlin/no/nav/syfo/persistering/db/PersisterDialogmeldingQueries.kt
- src/main/kotlin/no/nav/syfo/services/DialogmeldingDokumentService.kt
Sjekk om det finnes dialomgeldingdokument med samme sha som den nye meldingen.
Hvis duplikat, håndter det likt som før: Send negativ AppRec og gå videre til neste melding.
Gå ned til 1 pod for å unngå at duplikater kommer samtidig på hver sin pod.
Fjern Redis-sjekk, men behold lagring til redis inne i "handle"-metodene enn så lenge.
> Reject incoming message if duplicate

- src/main/kotlin/no/nav/syfo/application/BlockingApplicationRunner.kt
- src/main/kotlin/no/nav/syfo/model/DialogmeldingMapper.kt
- src/main/kotlin/no/nav/syfo/model/DialogmeldingType.kt
- src/main/kotlin/no/nav/syfo/validation/ValidateDialogMeldingKodeverk.kt
- src/test/kotlin/no/nav/syfo/ValidateDialogMeldingKodeverkTest.kt
Håndter null hvis meldingen har brukt et kodeverk/verdi vi ikke gjenkjenner, i stedet for å kaste exception.
Avvis melding hvis det er ukjent kodeverk, samme som når det er brukt kodeverk for feil meldingstype.
Bytt navn på valideringsmetoden.
> Handle unrecognized kodeverk

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/Bootstrap.kt
- src/main/kotlin/no/nav/syfo/Environment.kt
Bruk ny MQ server og queue manager.
Bruk brukernavn og passord til servicebrukeren for autentisering, siden den nå har fått tilgang til en egen MQ-gruppe.
Legg til eksplisitt autentisering i connectionFactory.
> Update MQ settings, use srv username/password for auth

- build.gradle.kts
These class dependecies are included in the list of dependencies. Also loading them in a buildscript is redundant.
> Remove redundant buildscript dependencies

- src/main/kotlin/no/nav/syfo/Bootstrap.kt
Fjerner konfig som er redundant og som lager støy i loggen med warnings som dette: 
WS-Addressing - failed to retrieve Message Addressing Properties from context
Response message does not contain WS-Addressing properties.  Not correlating response.
> Removing soap adressing feature

- src/main/kotlin/no/nav/syfo/handlestatus/HandleStatusInvalid.kt
- src/test/kotlin/no/nav/syfo/mock/DokarkivMock.kt
Journalføring feiler for pasienter der vi ikke finner aktørid, så må hoppe over journalføring for slike meldinger.
> Hopp over journalføring ved manglende aktoerId

- src/main/kotlin/no/nav/syfo/model/DialogmeldingMapper.kt
- src/test/kotlin/no/nav/syfo/dialogmelding/BlockingApplicationRunnerSpek.kt
Problemet oppstod pga av at valideringen er flyttet litt lengre ned i løypa, så da ble det noen nullpointer-feil (i stedet for at meldingene feilet kontrollert med negativ apprec).
> Håndtere at tekstnotat mangler

- src/main/kotlin/no/nav/syfo/application/BlockingApplicationRunner.kt
- src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
Let dialogmeldinger with large attachments pass without Joark timing out.
> Increase socket timeout to 1 minute for Dokarkiv requests

- src/main/kotlin/no/nav/syfo/apprec/ApprecMapper.kt
- src/main/kotlin/no/nav/syfo/handlestatus/HandleStatusInvalid.kt
This is the same error as team sykmelding has discovered and corrected.
https://github.com/navikt/syfosmapprec/commit/3d89361a8b0326936d01ec8d5ac1f341610c5982
> Use correct values in Apprec error, according to spec

- src/main/kotlin/no/nav/syfo/application/services/EmottakSubscriptionService.kt
Vil gjerne kjøre padm2 med denne logging først (for å verifisere at responsene vi får når subscription kjører i isproxy er tilsvarende det vi får fra padm2 i utgangspunktet).
Dvs vil kjøre med denne tilpasningen en liten stund før https://github.com/navikt/padm2/pull/104 merges,
> Log response from emottak subscription

- src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt
- src/main/kotlin/no/nav/syfo/handlestatus/HandleStatusInvalid.kt
- src/main/kotlin/no/nav/syfo/model/ValidationResult.kt
Da får vi med begrunnelse for avvisningen i pdfen som journalføres.
Fjern apprecMessage-feltet fra ValidationResult, siden det ikke lenger brukes.
> Return ValidationResult object from initial validation

- src/main/kotlin/no/nav/syfo/model/DialogmeldingMapper.kt
- src/test/kotlin/no/nav/syfo/dialogmelding/BlockingApplicationRunnerSpek.kt
- src/test/resources/dialogmelding_dialog_svar_foresporsel_om_pasient_invalid.xml
Noen varianter av ugyldig kodeverk ender i NullPointerException slik at meldingene havner på backout (og det genereres ikke apprec). 
Denne PR'en forbedrer dette slik at de lagres i databasen (som andre meldinger med ugyldig kodeverk), og får negativ apprec.
> Bugfix: improve handling of invalid kodeverk

- src/main/kotlin/no/nav/syfo/util/ExtractFromFellesFormat.kt
- src/test/kotlin/no/nav/syfo/kafka/DialogmeldingProducerTest.kt
Vi fikk en dialogmelding som feilet i dag siden den ikke kunne legges på Kafka-topic fordi meldingen er for stor. 
Viser seg at årsaken er vedlegg med mimetype image/jpg som ikke ble oppdaget og fjernet før padm2 forsøkte å legge på Kafka-topic.
> Bugfix: vedlegg with mimetype image/jpg

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Merger denne først for å skru av meldingsprosessering for padm2 på fss.
> Turn off message processing during migration to gcp

- src/main/kotlin/no/nav/syfo/client/DokArkivClient.kt
- src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
- src/main/kotlin/no/nav/syfo/client/KuhrSarClient.kt
- src/test/kotlin/no/nav/syfo/client/DokArkivClientTest.kt
For at httpClient skal oppføre seg som før - ref: https://ktor.io/docs/migrating-2.html#response-validation
Endret samtidig til `response.bodyAsChannel` der hvor vi brukte `response.content` før oppgradering.
> httpClient expects success

- src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt
- src/main/kotlin/no/nav/syfo/client/DokArkivClient.kt
- src/main/kotlin/no/nav/syfo/util/ExtractFromFellesFormat.kt
- src/test/kotlin/no/nav/syfo/dialogmelding/BlockingApplicationRunnerSpek.kt
- src/test/kotlin/no/nav/syfo/kafka/DialogmeldingProducerTest.kt
- src/test/kotlin/no/nav/syfo/mock/DokarkivMock.kt
Problemet med dialogmeldingen som feiler i padm2 nå er at hpr-nummeret til behandleren inneholder en '-', så det kan ikke brukes for journalføring.
Vi kan fint prosessere meldingen uten hprnr (det er ikke et påkrevd felt).
> Handle invalid hprnr

- src/main/resources/db/migration/V4_9__skip_kafka_publish_large_message.sql
Foreslår at vi løser problemet denne gangen med å ikke publisere meldingen på Kafka - det gjøres ved å bare sette et timestamp i den aktuelle kolonnen. Melding er en henvendelse fra lege som skal til Arena.
> Skip Kafka-publish for large message

- src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt
It's 11 digits, like 80000346168, so logback masks it before logging.
> Make tssID string non maskable

- src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt
- src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
Vi hadde et tilfelle der en dialogmeldiing ble avvist fordi behandleren ikke ble funnet av syfohelsenettproxy (404-feil), men dette var bare et sporadisk tilfelle (syfohelsenettproxy returnerte 200 for samme behandler både før og etter). 
Så for å redusere sannsynligheten for at dette skjer igjen foreslår jeg at vi gjør tilsvarende retry som ved andre feil også når responsen er 404.
> Retry if 4xx from syfohelsenettproxy

- .github/pull_request_template.md
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Team sykmelding skrev til oss på Slack, og de har flyttet appen til GCP. Derfor kan vi bytte ut litt config for å snakke med GCP-versjonen av appen i stedet for on-prem 🙌🏼
Noe jeg har glemt? Kan teste at det funker i dev først.
> IS-1645: Use servicediscovery for syfohelsenettproxy

- src/main/kotlin/no/nav/syfo/application/BlockingApplicationRunner.kt
- src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt
- src/main/kotlin/no/nav/syfo/application/api/ApiVedlegg.kt
- src/main/kotlin/no/nav/syfo/kafka/DialogmeldingProducer.kt
- src/main/kotlin/no/nav/syfo/util/JaxBUtils.kt
- src/test/kotlin/no/nav/syfo/ApprecMapperTest.kt
- src/test/kotlin/no/nav/syfo/CreateArenaDialogNotatTest.kt
- src/test/kotlin/no/nav/syfo/DialogmeldingMapperTest.kt
- src/test/kotlin/no/nav/syfo/ExtractFromFellesFormatTest.kt
- src/test/kotlin/no/nav/syfo/FromKiropraktorTest.kt
- src/test/kotlin/no/nav/syfo/ValidateDialogMeldingKodeverkTest.kt
- src/test/kotlin/no/nav/syfo/dialogmelding/DialogmeldingProcessorTssSpek.kt
- src/test/kotlin/no/nav/syfo/kafka/DialogmeldingProducerTest.kt
- src/test/kotlin/no/nav/syfo/services/EmottakServiceSpek.kt
Fikser kritisk sårbarhet fra code scanning: java/xxe
Se feks https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html
> Safe unmarshal

- src/main/kotlin/no/nav/syfo/application/RerunCronJob.kt
For å være litt mer robuste, så ønsker vi å spre de to cronjobbene ut litt i tid, ettersom de går like ofte. Bedre at de går litt alternerende enn samtidig hver gang.
> IS-1682: Move start of rerun cronjob so it does not start at the same time as arena cronjob

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Se slack: https://nav-it.slack.com/archives/G01ABN2E885/p1697809881164999
Vi fikk en warning i loggene når vi deployet padm2, fordi `name` ikke var gjenkjent blant annet.
> IS-1716: Remove unsupported yaml-format

- src/main/kotlin/no/nav/syfo/application/SendDialogmeldingArenaCronjob.kt
- src/main/kotlin/no/nav/syfo/handlestatus/HandleStatusOK.kt
- src/main/kotlin/no/nav/syfo/persistering/db/PersisterDialogmeldingQueries.kt
- src/main/resources/db/migration/V5_1__add_column_is_sendt_to_arena.sql
- src/main/resources/db/migration/V5_1__add_column_sendt_to_arena.sql
- src/test/kotlin/no/nav/syfo/TestDatabase.kt
- src/test/kotlin/no/nav/syfo/dialogmelding/SendDialogmeldingArenaCronjobSpek.kt
For å holde orden på hvilke meldinger vi ikke skal plukke opp i cronjobben fra https://github.com/navikt/padm2/pull/219, må vi ha et felt i databasen som sier om meldingen er sjekket (mot feks isbehandlerdialog), men ikke skal sendes. Hvis ikke vil den for alltid dukke opp i cronjobben siden meldingen vil slå ut på den sjekken som gjøres der.
Tanken her nå er at man har et flag som sier om den er sendt til arena eller ikke, og at den gamle `arena`-kolonnen (et timestamp) som sjekket dette før, nå skal holde orden på om arena-sending har blitt sjekket eller ikke. I fremtiden vil derfor alle få dette `arena`-feltet (med mindre det ble negativ apprec), og cronjobben vil ikke plukke opp disse lenger.
> IS-1731: Add column sent_to_arena-flag

- src/main/kotlin/no/nav/syfo/client/ArenaDialogNotat.kt
- src/main/kotlin/no/nav/syfo/client/SmgcpClient.kt
- src/main/kotlin/no/nav/syfo/services/ApprecService.kt
- src/main/kotlin/no/nav/syfo/util/JaxBUtils.kt
Oppdaget at det er en potensiell samtidighetskonflikt knyttet til fellesformatUnmarshaller. I motsetning til jaxb-context er marshall/unmarshall-objekter *ikke* trådsikre.
> IS-1748: Fix concurrency conflict

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/Bootstrap.kt
- src/main/kotlin/no/nav/syfo/Environment.kt
- src/main/kotlin/no/nav/syfo/application/BlockingApplicationRunner.kt
- src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt
- src/main/kotlin/no/nav/syfo/application/cronjob/CronjobLauncher.kt
- src/main/kotlin/no/nav/syfo/handlestatus/HandleStatusOK.kt
- src/main/kotlin/no/nav/syfo/services/ArenaDialogmeldingService.kt
- src/main/kotlin/no/nav/syfo/util/LoggingMeta.kt
- src/test/kotlin/no/nav/syfo/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/api/VedleggSystemApiSpek.kt
- src/test/kotlin/no/nav/syfo/dialogmelding/BlockingApplicationRunnerSpek.kt
- src/test/kotlin/no/nav/syfo/services/ArenaDialogmeldingServiceSpek.kt
Dialogmeldinger sendes nå til Arena via ny cronjob så vi kan slette litt gammel kode :tada:
> IS-1735: Remove send to arena code which is always toggled off

- build.gradle.kts
Hva er nytt / hva har blitt fikset?
> Bump postgres and other dependencies

- .nais/kafka/dialogmelding.yaml
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/Environment.kt
AAP må ha tilgang for å finne innkommende dialogmeldinger som er svar på dialogmeldinger de har sendt.
> IS-2812: Gi AAP tilgang til Kafka-topic og vedlegg-api

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/Environment.kt
- src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt
- src/main/kotlin/no/nav/syfo/services/JournalService.kt
- src/test/kotlin/no/nav/syfo/TestEnvironment.kt
Skrur av retry av journalføring i dev (i dag står dialogmeldingene og feiler i det uendelige dersom de er sendt inn på personer som mangler aktørid)
> IS-2643: Turn off JP-retry in dev

- src/main/kotlin/no/nav/syfo/application/DialogmeldingProcessor.kt
- src/main/kotlin/no/nav/syfo/model/DialogmeldingKodeverk.kt
- src/main/kotlin/no/nav/syfo/validation/ValidateDialogMeldingKodeverk.kt
- src/test/kotlin/no/nav/syfo/ValidateDialogMeldingKodeverkTest.kt
Legger på logging først for å verifisere at dette fanger opp de aktuelle tilfellene. 
Når det er verifisert: ny PR for å returnere false fra valideringen slik at det blir generert en negativ apprec.
> IS-3152: Invalid svar dialogmoteinnkalling

- src/main/kotlin/no/nav/syfo/validation/ValidateDialogMeldingKodeverk.kt
- src/test/kotlin/no/nav/syfo/CreateArenaDialogNotatTest.kt
- src/test/kotlin/no/nav/syfo/dialogmelding/BlockingApplicationRunnerSpek.kt
- src/test/resources/dialogmelding_dialog_svar_innkalling_dialogmote_invalid.xml
Negativ apprec når dialogmøtesvar kommer med forespørselsvar-kodeverk.
> IS-3152: Negative apprec when wrong combination

- src/main/kotlin/no/nav/syfo/client/ClamAvClient.kt
Vi får feil ved prosessering av dialogmelding.
Kopi av https://github.com/navikt/pale-2/commit/12945ca30c8f397b99ccdba047df8d93fbf65878
Se diskusjon: https://nav-it.slack.com/archives/C01958ML2M6/p1759472371348989
> IS-3455: Filename is quoted when it has whitspaces
